export const GET_RESET_PASSWORD_TOKEN = "GET_RESET_PASSWORD_TOKEN";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";
export const INVALID_EMAIL = "INVALID_EMAIL";
